CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "OpenIddictApplications" (
    "Id" uuid NOT NULL,
    "ApplicationType" character varying(50),
    "ClientId" character varying(100),
    "ClientSecret" text,
    "ClientType" character varying(50),
    "ConcurrencyToken" character varying(50),
    "ConsentType" character varying(50),
    "DisplayName" text,
    "DisplayNames" text,
    "JsonWebKeySet" text,
    "Permissions" text,
    "PostLogoutRedirectUris" text,
    "Properties" text,
    "RedirectUris" text,
    "Requirements" text,
    "Settings" text,
    CONSTRAINT "PK_OpenIddictApplications" PRIMARY KEY ("Id")
);

CREATE TABLE "OpenIddictScopes" (
    "Id" uuid NOT NULL,
    "ConcurrencyToken" character varying(50),
    "Description" text,
    "Descriptions" text,
    "DisplayName" text,
    "DisplayNames" text,
    "Name" character varying(200),
    "Properties" text,
    "Resources" text,
    CONSTRAINT "PK_OpenIddictScopes" PRIMARY KEY ("Id")
);

CREATE TABLE "OutboxMessages" (
    "Id" uuid NOT NULL,
    "EventName" character varying(200) NOT NULL,
    "AggregateType" character varying(200) NOT NULL,
    "AggregateId" uuid NOT NULL,
    "Payload" jsonb NOT NULL,
    "Status" character varying(100) NOT NULL,
    "Retries" integer NOT NULL,
    "Error" character varying(255),
    "OccurredOn" timestamp with time zone NOT NULL,
    "ProcessedOn" timestamp with time zone,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
);

CREATE TABLE "Permissions" (
    "Id" uuid NOT NULL,
    "CodeId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Workspaces" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    CONSTRAINT "PK_Workspaces" PRIMARY KEY ("Id")
);

CREATE TABLE "OpenIddictAuthorizations" (
    "Id" uuid NOT NULL,
    "ApplicationId" uuid,
    "ConcurrencyToken" character varying(50),
    "CreationDate" timestamp with time zone,
    "Properties" text,
    "Scopes" text,
    "Status" character varying(50),
    "Subject" character varying(400),
    "Type" character varying(50),
    CONSTRAINT "PK_OpenIddictAuthorizations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OpenIddictAuthorizations_OpenIddictApplications_Application~" FOREIGN KEY ("ApplicationId") REFERENCES "OpenIddictApplications" ("Id")
);

CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RolePermissions" (
    "Id" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    "PermissionId" uuid NOT NULL,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "WorkspaceId" uuid NOT NULL,
    "UserSettings" jsonb NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES "Workspaces" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "OpenIddictTokens" (
    "Id" uuid NOT NULL,
    "ApplicationId" uuid,
    "AuthorizationId" uuid,
    "ConcurrencyToken" character varying(50),
    "CreationDate" timestamp with time zone,
    "ExpirationDate" timestamp with time zone,
    "Payload" text,
    "Properties" text,
    "RedemptionDate" timestamp with time zone,
    "ReferenceId" character varying(100),
    "Status" character varying(50),
    "Subject" character varying(400),
    "Type" character varying(150),
    CONSTRAINT "PK_OpenIddictTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OpenIddictTokens_OpenIddictApplications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES "OpenIddictApplications" ("Id"),
    CONSTRAINT "FK_OpenIddictTokens_OpenIddictAuthorizations_AuthorizationId" FOREIGN KEY ("AuthorizationId") REFERENCES "OpenIddictAuthorizations" ("Id")
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    "Id" uuid NOT NULL,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "Permissions" ("Id", "CodeId", "CreatedBy", "CreatedOn", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedOn")
VALUES ('52b23446-4b62-497f-b8ef-b254be4a7570', 1, '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Allows administrator management operations.', TRUE, 'Can Manage', NULL, NULL);

INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedBy", "CreatedOn", "Description", "IsActive", "Name", "NormalizedName", "UpdatedBy", "UpdatedOn")
VALUES ('1cf3d7a5-b4b3-4b08-b3a8-b5c62f5266b4', '1cf3d7a5b4b34b08b3a8b5c62f5266b4', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default base user role.', TRUE, 'User', 'USER', NULL, NULL);
INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedBy", "CreatedOn", "Description", "IsActive", "Name", "NormalizedName", "UpdatedBy", "UpdatedOn")
VALUES ('38e983f9-e09f-4c6f-b5c9-2f8949b8c5fc', '38e983f9e09f4c6fb5c92f8949b8c5fc', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default cross-workspace super administrator role.', TRUE, 'SuperAdministrator', 'SUPERADMINISTRATOR', NULL, NULL);
INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedBy", "CreatedOn", "Description", "IsActive", "Name", "NormalizedName", "UpdatedBy", "UpdatedOn")
VALUES ('ebc29128-4abe-4456-9c09-f9348ddfe91c', 'ebc291284abe44569c09f9348ddfe91c', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default workspace-scoped administrator role.', TRUE, 'Administrator', 'ADMINISTRATOR', NULL, NULL);

INSERT INTO "Workspaces" ("Id", "CreatedBy", "CreatedOn", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedOn")
VALUES ('e3a2d95a-9d31-4232-b617-1ea4cdc65f88', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default personal workspace.', TRUE, 'Personal', NULL, NULL);

INSERT INTO "RolePermissions" ("Id", "CreatedBy", "CreatedOn", "Description", "IsActive", "PermissionId", "RoleId", "UpdatedBy", "UpdatedOn")
VALUES ('d0edb44d-1a1d-47f8-85fd-5998a2c0de0c', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default administrator permission assignment.', TRUE, '52b23446-4b62-497f-b8ef-b254be4a7570', 'ebc29128-4abe-4456-9c09-f9348ddfe91c', NULL, NULL);

CREATE UNIQUE INDEX "IX_OpenIddictApplications_ClientId" ON "OpenIddictApplications" ("ClientId");

CREATE INDEX "IX_OpenIddictAuthorizations_ApplicationId_Status_Subject_Type" ON "OpenIddictAuthorizations" ("ApplicationId", "Status", "Subject", "Type");

CREATE UNIQUE INDEX "IX_OpenIddictScopes_Name" ON "OpenIddictScopes" ("Name");

CREATE INDEX "IX_OpenIddictTokens_ApplicationId_Status_Subject_Type" ON "OpenIddictTokens" ("ApplicationId", "Status", "Subject", "Type");

CREATE INDEX "IX_OpenIddictTokens_AuthorizationId" ON "OpenIddictTokens" ("AuthorizationId");

CREATE UNIQUE INDEX "IX_OpenIddictTokens_ReferenceId" ON "OpenIddictTokens" ("ReferenceId");

CREATE UNIQUE INDEX "IX_Permissions_CodeId" ON "Permissions" ("CodeId");

CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");

CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");

CREATE UNIQUE INDEX "IX_RolePermissions_RoleId_PermissionId" ON "RolePermissions" ("RoleId", "PermissionId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");

CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");

CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");

CREATE UNIQUE INDEX "IX_UserRoles_Id" ON "UserRoles" ("Id");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE UNIQUE INDEX "IX_UserRoles_UserId_RoleId" ON "UserRoles" ("UserId", "RoleId");

CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");

CREATE INDEX "IX_Users_WorkspaceId" ON "Users" ("WorkspaceId");

CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260322092524_InitialIdentityFoundation', '10.0.3');

COMMIT;

START TRANSACTION;
INSERT INTO "Users" ("Id", "AccessFailedCount", "ConcurrencyStamp", "CreatedBy", "CreatedOn", "Description", "Email", "EmailConfirmed", "IsActive", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled", "UpdatedBy", "UpdatedOn", "UserName", "UserSettings", "WorkspaceId")
VALUES ('d2deace4-2350-42cd-bba6-c7b18cf54d39', 0, 'd2deace4-2350-42cd-bba6-c7b18cf54d39', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default system administrator account.', 'SystemAdministrator@opensaur.local', TRUE, TRUE, FALSE, NULL, 'SYSTEMADMINISTRATOR@OPENSAUR.LOCAL', 'SYSTEMADMINISTRATOR', 'AQAAAAIAAYagAAAAENLoUJMaZDYSIyqN+9f2mIif4gyyOql7xr05t+ucKjmRTuoTQWtNva/D0b80LGlKRA==', NULL, FALSE, 'd2deace4235042cdbba6c7b18cf54d39', FALSE, NULL, NULL, 'SystemAdministrator', '{}', 'e3a2d95a-9d31-4232-b617-1ea4cdc65f88');

INSERT INTO "UserRoles" ("RoleId", "UserId", "CreatedBy", "CreatedOn", "Description", "Id", "IsActive", "UpdatedBy", "UpdatedOn")
VALUES ('38e983f9-e09f-4c6f-b5c9-2f8949b8c5fc', 'd2deace4-2350-42cd-bba6-c7b18cf54d39', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default system administrator role assignment.', 'dcbe2a91-7e7f-4f7a-a053-f9553fcc2aba', TRUE, NULL, NULL);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260322103105_SeedSystemAdministrator', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "RequirePasswordChange" boolean NOT NULL DEFAULT FALSE;

UPDATE "Users" SET "RequirePasswordChange" = TRUE
WHERE "Id" = 'd2deace4-2350-42cd-bba6-c7b18cf54d39';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260322132732_RequirePasswordChangeOnUsers', '10.0.3');

COMMIT;

START TRANSACTION;
UPDATE "Users" SET "PasswordHash" = 'AQAAAAIAAYagAAAAEOFFiUu7B4wSzY7A4i1/VLOUnRjvSDE14MryEaaq4/og63kvvhceW3RF1F+hb+ETlg=='
WHERE "Id" = 'd2deace4-2350-42cd-bba6-c7b18cf54d39';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260322134105_UpdateSystemAdministratorSeedPassword', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Permissions" ADD "PermissionScopeId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

CREATE TABLE "PermissionScopes" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    CONSTRAINT "PK_PermissionScopes" PRIMARY KEY ("Id")
);

INSERT INTO "PermissionScopes" ("Id", "CreatedBy", "CreatedOn", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedOn")
VALUES ('7284f832-b4f0-4508-9c96-98ce6f87db6d', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Administrative capabilities for managing the identity service.', TRUE, 'Administrator', NULL, NULL);

UPDATE "Permissions" SET "Description" = 'Allows administrators to manage identity configuration and records.', "PermissionScopeId" = '7284f832-b4f0-4508-9c96-98ce6f87db6d'
WHERE "Id" = '52b23446-4b62-497f-b8ef-b254be4a7570';

INSERT INTO "Permissions" ("Id", "CodeId", "CreatedBy", "CreatedOn", "Description", "IsActive", "Name", "PermissionScopeId", "UpdatedBy", "UpdatedOn")
VALUES ('dd49a1d9-a22f-4906-9788-cd4e9f74af95', 2, '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Allows administrators to view identity configuration and records.', TRUE, 'Can View', '7284f832-b4f0-4508-9c96-98ce6f87db6d', NULL, NULL);

CREATE INDEX "IX_Permissions_PermissionScopeId" ON "Permissions" ("PermissionScopeId");

CREATE UNIQUE INDEX "IX_PermissionScopes_Name" ON "PermissionScopes" ("Name");

ALTER TABLE "Permissions" ADD CONSTRAINT "FK_Permissions_PermissionScopes_PermissionScopeId" FOREIGN KEY ("PermissionScopeId") REFERENCES "PermissionScopes" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260324084954_AddPermissionScopes', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Permissions" ADD "Code" character varying(200) NOT NULL DEFAULT '';

ALTER TABLE "Permissions" ADD "Rank" integer NOT NULL DEFAULT 0;

UPDATE "Permissions" SET "Code" = 'Administrator.CanManage', "Rank" = 2
WHERE "Id" = '52b23446-4b62-497f-b8ef-b254be4a7570';

UPDATE "Permissions" SET "Code" = 'Administrator.CanView', "Rank" = 1
WHERE "Id" = 'dd49a1d9-a22f-4906-9788-cd4e9f74af95';

CREATE UNIQUE INDEX "IX_Permissions_Code" ON "Permissions" ("Code");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260326191858_AddPermissionCodeAndRank', '10.0.3');

COMMIT;

START TRANSACTION;
CREATE TABLE "WorkspaceRoles" (
    "Id" uuid NOT NULL,
    "WorkspaceId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    "Description" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    CONSTRAINT "PK_WorkspaceRoles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkspaceRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkspaceRoles_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES "Workspaces" ("Id") ON DELETE RESTRICT
);

UPDATE "Roles" SET "Name" = 'Super Administrator', "NormalizedName" = 'SUPER ADMINISTRATOR'
WHERE "Id" = '38e983f9-e09f-4c6f-b5c9-2f8949b8c5fc';

INSERT INTO "WorkspaceRoles" ("Id", "CreatedBy", "CreatedOn", "Description", "IsActive", "RoleId", "UpdatedBy", "UpdatedOn", "WorkspaceId")
VALUES ('4dba0a76-675d-487d-9d0c-7e4bdbb98b7e', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default personal-workspace user role availability.', TRUE, '1cf3d7a5-b4b3-4b08-b3a8-b5c62f5266b4', NULL, NULL, 'e3a2d95a-9d31-4232-b617-1ea4cdc65f88');
INSERT INTO "WorkspaceRoles" ("Id", "CreatedBy", "CreatedOn", "Description", "IsActive", "RoleId", "UpdatedBy", "UpdatedOn", "WorkspaceId")
VALUES ('81a4f14f-27f9-4b8a-a360-b26e71877648', '67be05c0-1f88-4a2c-86f4-d97ad4589135', TIMESTAMPTZ '2026-03-22T00:00:00Z', 'Default personal-workspace administrator role availability.', TRUE, 'ebc29128-4abe-4456-9c09-f9348ddfe91c', NULL, NULL, 'e3a2d95a-9d31-4232-b617-1ea4cdc65f88');

CREATE UNIQUE INDEX "IX_WorkspaceRoles_Id" ON "WorkspaceRoles" ("Id");

CREATE INDEX "IX_WorkspaceRoles_RoleId" ON "WorkspaceRoles" ("RoleId");

CREATE UNIQUE INDEX "IX_WorkspaceRoles_WorkspaceId_RoleId" ON "WorkspaceRoles" ("WorkspaceId", "RoleId");

INSERT INTO "WorkspaceRoles" ("Id", "WorkspaceId", "RoleId", "Description", "IsActive", "CreatedBy", "CreatedOn", "UpdatedBy", "UpdatedOn")
SELECT
    (
        SUBSTRING(md5(workspaces."Id"::text || roles."Id"::text || 'workspace-role-backfill') FROM 1 FOR 8) || '-' ||
        SUBSTRING(md5(workspaces."Id"::text || roles."Id"::text || 'workspace-role-backfill') FROM 9 FOR 4) || '-' ||
        SUBSTRING(md5(workspaces."Id"::text || roles."Id"::text || 'workspace-role-backfill') FROM 13 FOR 4) || '-' ||
        SUBSTRING(md5(workspaces."Id"::text || roles."Id"::text || 'workspace-role-backfill') FROM 17 FOR 4) || '-' ||
        SUBSTRING(md5(workspaces."Id"::text || roles."Id"::text || 'workspace-role-backfill') FROM 21 FOR 12)
    )::uuid,
    workspaces."Id",
    roles."Id",
    'Backfilled workspace role availability.',
    TRUE,
    workspaces."CreatedBy",
    NOW(),
    NULL,
    NULL
FROM "Workspaces" AS workspaces
CROSS JOIN "Roles" AS roles
WHERE roles."IsActive" = TRUE
  AND REPLACE(COALESCE(roles."NormalizedName", ''), ' ', '') <> 'SUPERADMINISTRATOR'
  AND NOT EXISTS (
      SELECT 1
      FROM "WorkspaceRoles" AS workspaceRoles
      WHERE workspaceRoles."WorkspaceId" = workspaces."Id"
        AND workspaceRoles."RoleId" = roles."Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260329043521_AddWorkspaceRoleAvailability', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Workspaces" ADD "MaxActiveUsers" integer;

UPDATE "Workspaces" SET "MaxActiveUsers" = NULL
WHERE "Id" = 'e3a2d95a-9d31-4232-b617-1ea4cdc65f88';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260329105057_AddWorkspaceMaxActiveUsers', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "FirstName" text NOT NULL DEFAULT '';

ALTER TABLE "Users" ADD "LastName" text NOT NULL DEFAULT '';

UPDATE "Users" SET "FirstName" = 'System', "LastName" = 'Administrator'
WHERE "Id" = 'd2deace4-2350-42cd-bba6-c7b18cf54d39';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260329121421_AddUserFirstAndLastName', '10.0.3');

COMMIT;

