trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release
  dotnetSdkVersion: 10.0.x
  nodeVersion: 20.x
  webProject: Identity/src/OpenSaur.Identity.Web/OpenSaur.Identity.Web.csproj
  clientWorkingDirectory: Identity/src/OpenSaur.Identity.Web/client
  publishOutputDirectory: $(Build.ArtifactStagingDirectory)/webapp-publish
  dockerfileTemplate: Identity/devops/Dockerfile.artifact
  dockerHubServiceConnection: Docker Hub
  dockerRepository: duchihao/opensaur-indentity
  azureServiceConnection: Azure Service Connection
  containerAppResourceGroup: Home
  containerAppName: ca-identity

stages:
  - template: azure-pipelines.build-test-artifact.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      dotnetSdkVersion: $(dotnetSdkVersion)
      nodeVersion: $(nodeVersion)
      webProject: $(webProject)
      clientWorkingDirectory: $(clientWorkingDirectory)

  - template: azure-pipelines.artifact-to-dockerhub.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      dotnetSdkVersion: $(dotnetSdkVersion)
      nodeVersion: $(nodeVersion)
      webProject: $(webProject)
      publishOutputDirectory: $(publishOutputDirectory)
      dockerfileTemplate: $(dockerfileTemplate)
      dockerHubServiceConnection: $(dockerHubServiceConnection)
      dockerRepository: $(dockerRepository)

  - template: azure-pipelines.dockerhub-to-aca.yml
    parameters:
      azureServiceConnection: $(azureServiceConnection)
      containerAppResourceGroup: $(containerAppResourceGroup)
      containerAppName: $(containerAppName)
