trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release
  dotnetSdkVersion: 10.0.x
  nodeVersion: 20.x
  projectRoot: Identity
  webProject: Identity/src/OpenSaur.Identity.Web/OpenSaur.Identity.Web.csproj
  clientWorkingDirectory: Identity/src/OpenSaur.Identity.Web/client
  publishOutputDirectory: $(Build.ArtifactStagingDirectory)/webapp-publish
  publishArtifactName: webapp-publish

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BackendBuild
        displayName: Build Backend
        steps:
          - task: UseDotNet@2
            displayName: Install .NET SDK
            inputs:
              packageType: sdk
              version: $(dotnetSdkVersion)

          - task: DotNetCoreCLI@2
            displayName: 'Restore backend dependencies'
            inputs:
              command: 'restore'
              projects: '$(webProject)'
              feedsToUse: 'select'

          - task: DotNetCoreCLI@2
            displayName: 'Build backend'
            inputs:
              command: 'build'
              projects: '$(webProject)'
              arguments: '--configuration $(buildConfiguration) --no-restore'

      - job: FrontendBuild
        displayName: Build Frontend
        steps:
          - task: UseNode@1
            displayName: Install Node.js
            inputs:
              version: $(nodeVersion)

          - task: Npm@1
            displayName: Install frontend dependencies
            inputs:
              command: install
              workingDir: $(clientWorkingDirectory)

          - task: Npm@1
            displayName: Build frontend
            inputs:
              command: custom
              workingDir: $(clientWorkingDirectory)
              customCommand: run build

  - stage: Publish
    displayName: Publish Artifact
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Publish
        displayName: Publish Application
        steps:
          - task: DotNetCoreCLI@2
            displayName: Publish web application
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(webProject)'
              arguments: '--configuration $(buildConfiguration) --output $(publishOutputDirectory) /p:CompressionEnabled=false'
              zipAfterPublish: false
              modifyOutputPath: false

          - task: PublishPipelineArtifact@1
            displayName: Publish to artifact
            inputs:
              targetPath: $(publishOutputDirectory)
              artifact: $(publishArtifactName)
              publishLocation: pipeline
