trigger: none
pr: none

parameters:
  - name: offlineBuildMode
    type: string
    default: last
    values:
      - last
      - independent

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release
  dotnetSdkVersion: 10.0.x
  nodeVersion: 20.x
  webProject: CashPilot/src/OpenSaur.CashPilot.Web/OpenSaur.CashPilot.Web.csproj
  clientWorkingDirectory: CashPilot/src/OpenSaur.CashPilot.Web/client
  publishOutputDirectory: $(Build.ArtifactStagingDirectory)/webapp-publish
  dockerfileTemplate: CashPilot/devops/Dockerfile.artifact
  dockerHubServiceConnection: Docker Hub
  dockerRepository: duchihao/cashpilot
  azureServiceConnection: Azure Service Connection
  containerAppResourceGroup: Home
  containerAppName: ca-cashpilot

stages:
  - template: azure-pipelines.build-test-artifact.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      dotnetSdkVersion: $(dotnetSdkVersion)
      nodeVersion: $(nodeVersion)
      webProject: $(webProject)
      clientWorkingDirectory: $(clientWorkingDirectory)

  - template: azure-pipelines.artifact-to-dockerhub.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      dotnetSdkVersion: $(dotnetSdkVersion)
      nodeVersion: $(nodeVersion)
      webProject: $(webProject)
      clientWorkingDirectory: $(clientWorkingDirectory)
      publishOutputDirectory: $(publishOutputDirectory)
      dockerfileTemplate: $(dockerfileTemplate)
      dockerHubServiceConnection: $(dockerHubServiceConnection)
      dockerRepository: $(dockerRepository)

  - template: azure-pipelines.dockerhub-to-aca.yml
    parameters:
      azureServiceConnection: $(azureServiceConnection)
      containerAppResourceGroup: $(containerAppResourceGroup)
      containerAppName: $(containerAppName)

  - template: azure-pipelines.publish-static-web.yml
    parameters:
      azureServiceConnection: $(azureServiceConnection)
      storageAccountName: cashpilot
      storageContainerName: $web
      nodeVersion: $(nodeVersion)
      clientWorkingDirectory: $(clientWorkingDirectory)
      offlineBuildMode: ${{ parameters.offlineBuildMode }}
