FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app
ENV ASPNETCORE_HTTP_PORTS=8080

EXPOSE 8080

COPY . .

RUN mkdir -p /app/certs \
    && chmod 700 /app/certs \
    && chmod 755 /app/container-entrypoint.sh \
    && chown -R $APP_UID /app

USER $APP_UID

ENTRYPOINT ["./container-entrypoint.sh"]
