export const resources = {
  "en-US": {
    translation: {
      "account.changePassword": "Change password",
      "account.logout": "Logout",
      "account.myProfile": "My Profile",
      "account.openMenu": "Open account menu",
      "account.settings": "Settings",
      "account.signingOut": "Logging out...",
      "apiErrors.auth_invalid_credentials": "Sign in failed. Check your credentials and try again.",
      "apiErrors.conflict": "The request conflicts with the current state.",
      "apiErrors.forbidden": "You do not have permission to perform this action.",
      "apiErrors.not_found": "The requested resource could not be found.",
      "apiErrors.server_error": "The server could not complete the request.",
      "apiErrors.unauthorized": "Authentication is required.",
      "apiErrors.user_workspace_capacity_reached": "The workspace has reached its active user limit.",
      "apiErrors.validation_error": "The request contains invalid values.",
      "auth.back": "Back",
      "auth.continueIssuerLogin": "Continue to Sign In",
      "auth.issuerExchangeFailedDetail": "The hosted sign-in completed, but the local app could not finish the issuer-backed session exchange. Review the issuer URL, client registration, and token-endpoint reachability, then retry manually.",
      "auth.issuerExchangeFailedTitle": "The local app could not finish signing you in.",
      "auth.issuerRedirectHint": "Continue on the issuer-hosted sign-in page if the browser does not redirect automatically.",
      "auth.preparingAccount": "Preparing your account...",
      "auth.preparingSession": "Preparing your session...",
      "auth.signingInDescription": "Please wait while we sign you in.",
      "auth.signingInTitle": "Signing you in",
      "changePassword.confirmPassword": "Confirm new password",
      "changePassword.confirmPasswordRequired": "Please confirm your new password.",
      "changePassword.currentPassword": "Current password",
      "changePassword.currentPasswordRequired": "Current password is required.",
      "changePassword.description": "Update your password to continue.",
      "changePassword.error": "Password update failed. Check the current password and try again.",
      "changePassword.newPassword": "New password",
      "changePassword.newPasswordRequired": "New password is required.",
      "changePassword.passwordsMustMatch": "Passwords must match.",
      "changePassword.submit": "Update password",
      "changePassword.submitting": "Updating password...",
      "changePassword.title": "Change password",
      "common.active": "Active",
      "common.all": "All",
      "common.applyFilters": "Apply filters",
      "common.applyingFilters": "Applying filters...",
      "common.cancel": "Cancel",
      "common.comingSoon": "Coming soon",
      "common.continue": "Continue",
      "common.continuing": "Continuing...",
      "common.create": "Create",
      "common.currentWorkspace": "the current workspace",
      "common.edit": "Edit",
      "common.filter": "Filter",
      "common.hidePassword": "Hide password",
      "common.inactive": "Inactive",
      "common.loading": "Loading...",
      "common.resetFilters": "Reset filters",
      "common.retry": "Retry",
      "common.save": "Save",
      "common.saving": "Saving...",
      "common.searchActiveRoles": "Search active roles",
      "common.showPassword": "Show password",
      "home.activeUsers": "Active users",
      "home.activeWorkspaces": "Active workspaces",
      "home.availableRoles": "Available roles",
      "home.dashboardUnavailable": "Dashboard unavailable",
      "home.dashboardUnavailableDetail": "The dashboard summary could not be loaded right now.",
      "home.inactiveUsers": "Inactive users",
      "home.licenseUsage": "License usage",
      "home.loadingSummary": "Loading dashboard summary...",
      "home.quickActions": "Quick actions",
      "home.quickActions.globalDescription": "Open the global administration surfaces for workspace, role, and user operations.",
      "home.quickActions.openRoleAssignments": "Open role assignments",
      "home.quickActions.openUsers": "Open users",
      "home.quickActions.openWorkspaces": "Open workspaces",
      "home.quickActions.roleCatalog": "Manage role catalog",
      "home.quickActions.workspaceDescription": "Manage users and roles for the current workspace.",
      "home.roleCatalog": "Role catalog",
      "home.title": "Dashboard",
      "home.totalWorkspaces": "Total workspaces",
      "home.unlimited": "Unlimited",
      "login.description": "Sign in to continue and pick up where you left off.",
      "login.error": "Sign in failed. Check your credentials and try again.",
      "login.passwordLabel": "Password",
      "login.passwordRequired": "Password is required.",
      "login.submit": "Sign in",
      "login.submitting": "Signing in...",
      "login.title": "Sign in",
      "login.userNameLabel": "Username",
      "login.userNameRequired": "User name is required.",
      "nav.dashboard": "Dashboard",
      "nav.roleAssignments": "Role Assignments",
      "nav.roles": "Roles",
      "nav.users": "Users",
      "nav.workspaces": "Workspace",
      "profile.currentLocale": "Current locale",
      "profile.currentTimeZone": "Current time zone",
      "profile.email": "Email",
      "profile.firstName": "First name",
      "profile.lastName": "Last name",
      "profile.roles": "Roles",
      "profile.subtitle": "Review the account and workspace context for your current session.",
      "profile.title": "My Profile",
      "profile.userName": "User name",
      "profile.workspace": "Workspace",
      "rolePreview.moreRolesAriaLabel": "Show {{count}} more {{roleLabel}}",
      "rolePreview.role": "role",
      "rolePreview.roles": "roles",
      "roleAssignments.assignmentCandidatesLoadError": "We couldn't load the assignment candidates right now.",
      "roleAssignments.assignmentLoadError": "We couldn't load the role assignments right now.",
      "roleAssignments.description": "Manage assigned users for roles in {{workspaceName}}.",
      "roleAssignments.drawer.assignedUsers": "Assigned users",
      "roleAssignments.drawer.close": "Close role assignments form",
      "roleAssignments.drawer.loading": "Loading role assignments...",
      "roleAssignments.drawer.noMatchingUsers": "No matching active users.",
      "roleAssignments.drawer.remove": "Remove",
      "roleAssignments.drawer.searchUsers": "Search active users",
      "roleAssignments.drawer.user": "User",
      "roleAssignments.empty.description": "There are no roles available to assign in the current workspace.",
      "roleAssignments.empty.title": "No roles available",
      "roleAssignments.error": "We couldn't save the role assignments. Please try again.",
      "roleAssignments.loading": "Loading roles...",
      "roleAssignments.retryLoad": "We couldn't load the role assignments right now.",
      "roleAssignments.subtitle": "Manage assigned users for roles in {{workspaceName}}.",
      "roleAssignments.table.actions": "Actions",
      "roleAssignments.table.description": "Description",
      "roleAssignments.table.edit": "Edit",
      "roleAssignments.table.editAssignments": "Edit assignments",
      "roleAssignments.table.name": "Name",
      "roleAssignments.table.status": "Status",
      "roleAssignments.title": "Role Assignments",
      "roles.description": "Manage global role definitions and permission mapping from one place.",
      "roles.empty.description": "Create the first role to define permissions for managed users.",
      "roles.empty.title": "No roles yet",
      "roles.error": "We couldn't save the role. Please try again.",
      "roles.filters.close": "Close role filters",
      "roles.filters.search": "Search roles",
      "roles.filters.status": "Role status",
      "roles.filters.title": "Filter roles",
      "roles.form.activeAriaLabel": "Role is active",
      "roles.form.activeLabel": "Role is active",
      "roles.form.close": "Close role form",
      "roles.form.createTitle": "Create role",
      "roles.form.description": "Description",
      "roles.form.editTitle": "Edit role",
      "roles.form.loading": "Loading role...",
      "roles.form.name": "Role name",
      "roles.form.nameRequired": "Role name is required.",
      "roles.form.permissionScope": "Permission scope",
      "roles.form.permissions": "Permissions",
      "roles.form.role": "Role",
      "roles.listError": "We couldn't load the role list right now.",
      "roles.loading": "Loading roles...",
      "roles.table.actions": "Actions",
      "roles.table.description": "Description",
      "roles.table.edit": "Edit",
      "roles.table.editAria": "Edit role",
      "roles.table.name": "Name",
      "roles.table.status": "Status",
      "roles.title": "Roles",
      "settings.error": "We couldn't save your settings right now.",
      "settings.language.english": "English (United States)",
      "settings.language.vietnamese": "Vietnamese",
      "settings.locale": "Locale",
      "settings.previewDescription": "Preview how dates and times are displayed with the selected language and time zone.",
      "settings.previewTitle": "Date and time preview",
      "settings.save": "Save",
      "settings.saved": "Settings saved.",
      "settings.saving": "Saving...",
      "settings.subtitle": "Manage language and time preferences for your account.",
      "settings.timeZone": "Time zone",
      "settings.title": "Settings",
      "shell.copyright": "Copyright (c) {{year}}",
      "shell.currentUser": "Current user",
      "shell.exitImpersonation": "Exit impersonation",
      "shell.exitImpersonationError": "We couldn't exit impersonation. Please try again.",
      "shell.impersonationBanner": "You are currently impersonating <strong>{{userName}}</strong> in <strong>{{workspaceName}}</strong>.",
      "shell.impersonationFallbackUser": "this user",
      "shell.openNavigation": "Open navigation",
      "shell.primaryNavigation": "Primary navigation",
      "shell.protectedWorkspace": "Protected workspace",
      "users.createError": "We couldn't create the user. Please try again.",
      "users.description": "Manage users and assigned roles in {{workspaceName}}.",
      "users.empty.description": "Create the first user for the current workspace.",
      "users.empty.title": "No users yet",
      "users.error": "We couldn't save the user. Please try again.",
      "users.filters.close": "Close user filters",
      "users.filters.search": "Search users",
      "users.filters.status": "User status",
      "users.filters.title": "Filter users",
      "users.form.activeAriaLabel": "User is active",
      "users.form.activeLabel": "User is active",
      "users.form.assignedRoles": "Assigned Roles",
      "users.form.close": "Close user form",
      "users.form.createTitle": "Create user",
      "users.form.description": "Description",
      "users.form.editTitle": "Edit user",
      "users.form.email": "Email",
      "users.form.emailRequired": "Email is required.",
      "users.form.firstName": "First name",
      "users.form.lastName": "Last name",
      "users.form.loading": "Loading user...",
      "users.form.role": "Role",
      "users.form.temporaryPassword": "Temporary password",
      "users.form.temporaryPasswordRequired": "Temporary password is required.",
      "users.form.user": "User",
      "users.form.userName": "User name",
      "users.form.userNameRequired": "User name is required.",
      "users.listError": "We couldn't load the user list right now.",
      "users.loading": "Loading users...",
      "users.noRoles": "No roles",
      "users.roleAssignmentsError": "We couldn't save the user role assignments. Please try again.",
      "users.table.actions": "Actions",
      "users.table.edit": "Edit",
      "users.table.editAria": "Edit user",
      "users.table.email": "Email",
      "users.table.roles": "Roles",
      "users.table.status": "Status",
      "users.table.userName": "User name",
      "users.title": "Users",
      "workspaces.createError": "We couldn't create the workspace. Please try again.",
      "workspaces.description": "Manage workspace access surfaces, activation state, and future administration flows from one place.",
      "workspaces.empty.description": "Create the first workspace to start organizing access and administration.",
      "workspaces.empty.title": "No workspaces yet",
      "workspaces.error": "We couldn't save the workspace. Please try again.",
      "workspaces.filters.close": "Close workspace filters",
      "workspaces.filters.search": "Search workspaces",
      "workspaces.filters.status": "Workspace status",
      "workspaces.filters.title": "Filter workspaces",
      "workspaces.form.activeAriaLabel": "Workspace is active",
      "workspaces.form.activeLabel": "Workspace is active",
      "workspaces.form.assignedRoles": "Assigned roles",
      "workspaces.form.close": "Close workspace form",
      "workspaces.form.createTitle": "Create workspace",
      "workspaces.form.description": "Description",
      "workspaces.form.editTitle": "Edit workspace",
      "workspaces.form.loading": "Loading workspace...",
      "workspaces.form.maxActiveUsers": "Max active users",
      "workspaces.form.maxActiveUsersValidation": "Max active users must be zero or greater.",
      "workspaces.form.name": "Workspace name",
      "workspaces.form.nameRequired": "Workspace name is required.",
      "workspaces.form.searchRoles": "Search active roles",
      "workspaces.impersonation.cancel": "Cancel",
      "workspaces.impersonation.close": "Close workspace impersonation dialog",
      "workspaces.impersonation.continue": "Continue",
      "workspaces.impersonation.continuing": "Continuing...",
      "workspaces.impersonation.error": "We couldn't start impersonation. Please try again.",
      "workspaces.impersonation.loadError": "We couldn't load the workspace users right now.",
      "workspaces.impersonation.loadingUsers": "Loading available users...",
      "workspaces.impersonation.noMatchingUsers": "No matching users.",
      "workspaces.impersonation.searchUsers": "Search users",
      "workspaces.impersonation.title": "Login as",
      "workspaces.impersonation.user": "User",
      "workspaces.impersonation.workspace": "Workspace",
      "workspaces.listError": "We couldn't load the workspace list right now.",
      "workspaces.loading": "Loading workspaces...",
      "workspaces.loginAs": "Login as",
      "workspaces.noRoles": "No roles",
      "workspaces.table.actions": "Actions",
      "workspaces.table.description": "Description",
      "workspaces.table.edit": "Edit",
      "workspaces.table.editAria": "Edit workspace",
      "workspaces.table.name": "Name",
      "workspaces.table.roles": "Roles",
      "workspaces.table.status": "Status",
      "workspaces.title": "Workspace"
    }
  },
  "vi-VN": {
    translation: {
      "account.changePassword": "Đổi mật khẩu",
      "account.logout": "Đăng xuất",
      "account.myProfile": "Hồ sơ của tôi",
      "account.openMenu": "Mở menu tài khoản",
      "account.settings": "Cài đặt",
      "account.signingOut": "Đang đăng xuất...",
      "apiErrors.auth_invalid_credentials": "Đăng nhập thất bại. Hãy kiểm tra lại thông tin đăng nhập.",
      "apiErrors.conflict": "Yêu cầu xung đột với trạng thái hiện tại.",
      "apiErrors.forbidden": "Bạn không có quyền thực hiện thao tác này.",
      "apiErrors.not_found": "Không tìm thấy tài nguyên được yêu cầu.",
      "apiErrors.server_error": "Máy chủ không thể hoàn tất yêu cầu.",
      "apiErrors.unauthorized": "Yêu cầu cần có phiên đăng nhập hợp lệ.",
      "apiErrors.user_workspace_capacity_reached": "Không gian làm việc đã đạt giới hạn người dùng đang hoạt động.",
      "apiErrors.validation_error": "Yêu cầu chứa dữ liệu không hợp lệ.",
      "auth.back": "Quay lại",
      "auth.continueIssuerLogin": "Tiếp tục đăng nhập",
      "auth.issuerExchangeFailedDetail": "Phiên đăng nhập trên máy chủ phát hành đã hoàn tất, nhưng ứng dụng cục bộ không thể hoàn tất việc trao đổi phiên dựa trên nhà phát hành. Hãy kiểm tra URL của nhà phát hành, cấu hình client và khả năng truy cập đến token endpoint rồi thử lại thủ công.",
      "auth.issuerExchangeFailedTitle": "Ứng dụng cục bộ không thể hoàn tất đăng nhập cho bạn.",
      "auth.issuerRedirectHint": "Hãy tiếp tục trên trang đăng nhập do nhà phát hành lưu trữ nếu trình duyệt không tự động chuyển hướng.",
      "auth.preparingAccount": "Đang chuẩn bị tài khoản của bạn...",
      "auth.preparingSession": "Đang chuẩn bị phiên đăng nhập...",
      "auth.signingInDescription": "Vui lòng chờ trong khi chúng tôi đăng nhập cho bạn.",
      "auth.signingInTitle": "Đang đăng nhập",
      "changePassword.confirmPassword": "Xác nhận mật khẩu mới",
      "changePassword.confirmPasswordRequired": "Vui lòng xác nhận mật khẩu mới.",
      "changePassword.currentPassword": "Mật khẩu hiện tại",
      "changePassword.currentPasswordRequired": "Mật khẩu hiện tại là bắt buộc.",
      "changePassword.description": "Cập nhật mật khẩu để tiếp tục.",
      "changePassword.error": "Cập nhật mật khẩu thất bại. Hãy kiểm tra lại mật khẩu hiện tại.",
      "changePassword.newPassword": "Mật khẩu mới",
      "changePassword.newPasswordRequired": "Mật khẩu mới là bắt buộc.",
      "changePassword.passwordsMustMatch": "Mật khẩu xác nhận phải khớp.",
      "changePassword.submit": "Cập nhật mật khẩu",
      "changePassword.submitting": "Đang cập nhật mật khẩu...",
      "changePassword.title": "Đổi mật khẩu",
      "common.active": "Hoạt động",
      "common.all": "Tất cả",
      "common.applyFilters": "Áp dụng bộ lọc",
      "common.applyingFilters": "Đang áp dụng bộ lọc...",
      "common.cancel": "Hủy",
      "common.comingSoon": "Sắp ra mắt",
      "common.continue": "Tiếp tục",
      "common.continuing": "Đang tiếp tục...",
      "common.create": "Tạo",
      "common.currentWorkspace": "không gian làm việc hiện tại",
      "common.edit": "Chỉnh sửa",
      "common.filter": "Lọc",
      "common.hidePassword": "Ẩn mật khẩu",
      "common.inactive": "Không hoạt động",
      "common.loading": "Đang tải...",
      "common.resetFilters": "Đặt lại bộ lọc",
      "common.retry": "Thử lại",
      "common.save": "Lưu",
      "common.saving": "Đang lưu...",
      "common.searchActiveRoles": "Tìm kiếm vai trò đang hoạt động",
      "common.showPassword": "Hiện mật khẩu",
      "home.activeUsers": "Người dùng đang hoạt động",
      "home.activeWorkspaces": "Không gian làm việc đang hoạt động",
      "home.availableRoles": "Vai trò khả dụng",
      "home.dashboardUnavailable": "Không thể tải bảng điều khiển",
      "home.dashboardUnavailableDetail": "Không thể tải dữ liệu tổng quan của bảng điều khiển lúc này.",
      "home.inactiveUsers": "Người dùng không hoạt động",
      "home.licenseUsage": "Mức sử dụng giấy phép",
      "home.loadingSummary": "Đang tải dữ liệu tổng quan...",
      "home.quickActions": "Thao tác nhanh",
      "home.quickActions.globalDescription": "Mở các màn hình quản trị toàn cục cho không gian làm việc, vai trò và người dùng.",
      "home.quickActions.openRoleAssignments": "Mở phân công vai trò",
      "home.quickActions.openUsers": "Mở người dùng",
      "home.quickActions.openWorkspaces": "Mở không gian làm việc",
      "home.quickActions.roleCatalog": "Quản lý danh mục vai trò",
      "home.quickActions.workspaceDescription": "Quản lý người dùng và vai trò cho không gian làm việc hiện tại.",
      "home.roleCatalog": "Danh mục vai trò",
      "home.title": "Bảng điều khiển",
      "home.totalWorkspaces": "Tổng số không gian làm việc",
      "home.unlimited": "Không giới hạn",
      "login.description": "Đăng nhập để tiếp tục và quay lại công việc của bạn.",
      "login.error": "Đăng nhập thất bại. Hãy kiểm tra lại thông tin đăng nhập.",
      "login.passwordLabel": "Mật khẩu",
      "login.passwordRequired": "Mật khẩu là bắt buộc.",
      "login.submit": "Đăng nhập",
      "login.submitting": "Đang đăng nhập...",
      "login.title": "Đăng nhập",
      "login.userNameLabel": "Tên đăng nhập",
      "login.userNameRequired": "Tên đăng nhập là bắt buộc.",
      "nav.dashboard": "Bảng điều khiển",
      "nav.roleAssignments": "Phân công vai trò",
      "nav.roles": "Vai trò",
      "nav.users": "Người dùng",
      "nav.workspaces": "Không gian làm việc",
      "profile.currentLocale": "Ngôn ngữ hiện tại",
      "profile.currentTimeZone": "Múi giờ hiện tại",
      "profile.email": "Email",
      "profile.firstName": "Tên",
      "profile.lastName": "Họ",
      "profile.roles": "Vai trò",
      "profile.subtitle": "Xem thông tin tài khoản và ngữ cảnh không gian làm việc của phiên hiện tại.",
      "profile.title": "Hồ sơ của tôi",
      "profile.userName": "Tên đăng nhập",
      "profile.workspace": "Không gian làm việc",
      "rolePreview.moreRolesAriaLabel": "Hiển thị thêm {{count}} {{roleLabel}}",
      "rolePreview.role": "vai trò",
      "rolePreview.roles": "vai trò",
      "roleAssignments.assignmentCandidatesLoadError": "Không thể tải danh sách người dùng để gán lúc này.",
      "roleAssignments.assignmentLoadError": "Không thể tải phân công vai trò lúc này.",
      "roleAssignments.description": "Quản lý người dùng được gán cho vai trò trong {{workspaceName}}.",
      "roleAssignments.drawer.assignedUsers": "Người dùng được gán",
      "roleAssignments.drawer.close": "Đóng biểu mẫu phân công vai trò",
      "roleAssignments.drawer.loading": "Đang tải phân công vai trò...",
      "roleAssignments.drawer.noMatchingUsers": "Không có người dùng đang hoạt động phù hợp.",
      "roleAssignments.drawer.remove": "Xóa",
      "roleAssignments.drawer.searchUsers": "Tìm kiếm người dùng đang hoạt động",
      "roleAssignments.drawer.user": "Người dùng",
      "roleAssignments.empty.description": "Không có vai trò nào khả dụng để gán trong không gian làm việc hiện tại.",
      "roleAssignments.empty.title": "Không có vai trò khả dụng",
      "roleAssignments.error": "Không thể lưu phân công vai trò. Vui lòng thử lại.",
      "roleAssignments.loading": "Đang tải vai trò...",
      "roleAssignments.retryLoad": "Không thể tải phân công vai trò lúc này.",
      "roleAssignments.subtitle": "Quản lý người dùng được gán cho vai trò trong {{workspaceName}}.",
      "roleAssignments.table.actions": "Thao tác",
      "roleAssignments.table.description": "Mô tả",
      "roleAssignments.table.edit": "Chỉnh sửa",
      "roleAssignments.table.editAssignments": "Chỉnh sửa phân công",
      "roleAssignments.table.name": "Tên",
      "roleAssignments.table.status": "Trạng thái",
      "roleAssignments.title": "Phân công vai trò",
      "roles.description": "Quản lý định nghĩa vai trò toàn cục và ánh xạ quyền tại một nơi.",
      "roles.empty.description": "Tạo vai trò đầu tiên để xác định quyền cho người dùng được quản lý.",
      "roles.empty.title": "Chưa có vai trò",
      "roles.error": "Không thể lưu vai trò. Vui lòng thử lại.",
      "roles.filters.close": "Đóng bộ lọc vai trò",
      "roles.filters.search": "Tìm kiếm vai trò",
      "roles.filters.status": "Trạng thái vai trò",
      "roles.filters.title": "Lọc vai trò",
      "roles.form.activeAriaLabel": "Vai trò đang hoạt động",
      "roles.form.activeLabel": "Vai trò đang hoạt động",
      "roles.form.close": "Đóng biểu mẫu vai trò",
      "roles.form.createTitle": "Tạo vai trò",
      "roles.form.description": "Mô tả",
      "roles.form.editTitle": "Chỉnh sửa vai trò",
      "roles.form.loading": "Đang tải vai trò...",
      "roles.form.name": "Tên vai trò",
      "roles.form.nameRequired": "Tên vai trò là bắt buộc.",
      "roles.form.permissionScope": "Phạm vi quyền",
      "roles.form.permissions": "Quyền",
      "roles.form.role": "Vai trò",
      "roles.listError": "Không thể tải danh sách vai trò lúc này.",
      "roles.loading": "Đang tải vai trò...",
      "roles.table.actions": "Thao tác",
      "roles.table.description": "Mô tả",
      "roles.table.edit": "Chỉnh sửa",
      "roles.table.editAria": "Chỉnh sửa vai trò",
      "roles.table.name": "Tên",
      "roles.table.status": "Trạng thái",
      "roles.title": "Vai trò",
      "settings.error": "Không thể lưu cài đặt của bạn lúc này.",
      "settings.language.english": "Tiếng Anh (Hoa Kỳ)",
      "settings.language.vietnamese": "Tiếng Việt",
      "settings.locale": "Ngôn ngữ",
      "settings.previewDescription": "Xem trước cách ngày giờ được hiển thị với ngôn ngữ và múi giờ đã chọn.",
      "settings.previewTitle": "Xem trước ngày và giờ",
      "settings.save": "Lưu",
      "settings.saved": "Đã lưu cài đặt.",
      "settings.saving": "Đang lưu...",
      "settings.subtitle": "Quản lý ngôn ngữ và múi giờ cho tài khoản của bạn.",
      "settings.timeZone": "Múi giờ",
      "settings.title": "Cài đặt",
      "shell.copyright": "Bản quyền (c) {{year}}",
      "shell.currentUser": "Người dùng hiện tại",
      "shell.exitImpersonation": "Thoát chế độ mạo danh",
      "shell.exitImpersonationError": "Không thể thoát chế độ mạo danh. Vui lòng thử lại.",
      "shell.impersonationBanner": "Bạn hiện đang mạo danh <strong>{{userName}}</strong> trong <strong>{{workspaceName}}</strong>.",
      "shell.impersonationFallbackUser": "người dùng này",
      "shell.openNavigation": "Mở điều hướng",
      "shell.primaryNavigation": "Điều hướng chính",
      "shell.protectedWorkspace": "Không gian làm việc được bảo vệ",
      "users.createError": "Không thể tạo người dùng. Vui lòng thử lại.",
      "users.description": "Quản lý người dùng và vai trò được gán trong {{workspaceName}}.",
      "users.empty.description": "Tạo người dùng đầu tiên cho không gian làm việc hiện tại.",
      "users.empty.title": "Chưa có người dùng",
      "users.error": "Không thể lưu người dùng. Vui lòng thử lại.",
      "users.filters.close": "Đóng bộ lọc người dùng",
      "users.filters.search": "Tìm kiếm người dùng",
      "users.filters.status": "Trạng thái người dùng",
      "users.filters.title": "Lọc người dùng",
      "users.form.activeAriaLabel": "Người dùng đang hoạt động",
      "users.form.activeLabel": "Người dùng đang hoạt động",
      "users.form.assignedRoles": "Vai trò được gán",
      "users.form.close": "Đóng biểu mẫu người dùng",
      "users.form.createTitle": "Tạo người dùng",
      "users.form.description": "Mô tả",
      "users.form.editTitle": "Chỉnh sửa người dùng",
      "users.form.email": "Email",
      "users.form.emailRequired": "Email là bắt buộc.",
      "users.form.firstName": "Tên",
      "users.form.lastName": "Họ",
      "users.form.loading": "Đang tải người dùng...",
      "users.form.role": "Vai trò",
      "users.form.temporaryPassword": "Mật khẩu tạm thời",
      "users.form.temporaryPasswordRequired": "Mật khẩu tạm thời là bắt buộc.",
      "users.form.user": "Người dùng",
      "users.form.userName": "Tên đăng nhập",
      "users.form.userNameRequired": "Tên đăng nhập là bắt buộc.",
      "users.listError": "Không thể tải danh sách người dùng lúc này.",
      "users.loading": "Đang tải người dùng...",
      "users.noRoles": "Không có vai trò",
      "users.roleAssignmentsError": "Không thể lưu phân công vai trò của người dùng. Vui lòng thử lại.",
      "users.table.actions": "Thao tác",
      "users.table.edit": "Chỉnh sửa",
      "users.table.editAria": "Chỉnh sửa người dùng",
      "users.table.email": "Email",
      "users.table.roles": "Vai trò",
      "users.table.status": "Trạng thái",
      "users.table.userName": "Tên đăng nhập",
      "users.title": "Người dùng",
      "workspaces.createError": "Không thể tạo không gian làm việc. Vui lòng thử lại.",
      "workspaces.description": "Quản lý quyền truy cập, trạng thái hoạt động và các luồng quản trị trong tương lai tại một nơi.",
      "workspaces.empty.description": "Tạo không gian làm việc đầu tiên để bắt đầu tổ chức quyền truy cập và quản trị.",
      "workspaces.empty.title": "Chưa có không gian làm việc",
      "workspaces.error": "Không thể lưu không gian làm việc. Vui lòng thử lại.",
      "workspaces.filters.close": "Đóng bộ lọc không gian làm việc",
      "workspaces.filters.search": "Tìm kiếm không gian làm việc",
      "workspaces.filters.status": "Trạng thái không gian làm việc",
      "workspaces.filters.title": "Lọc không gian làm việc",
      "workspaces.form.activeAriaLabel": "Không gian làm việc đang hoạt động",
      "workspaces.form.activeLabel": "Không gian làm việc đang hoạt động",
      "workspaces.form.assignedRoles": "Vai trò được gán",
      "workspaces.form.close": "Đóng biểu mẫu không gian làm việc",
      "workspaces.form.createTitle": "Tạo không gian làm việc",
      "workspaces.form.description": "Mô tả",
      "workspaces.form.editTitle": "Chỉnh sửa không gian làm việc",
      "workspaces.form.loading": "Đang tải không gian làm việc...",
      "workspaces.form.maxActiveUsers": "Số người dùng đang hoạt động tối đa",
      "workspaces.form.maxActiveUsersValidation": "Số người dùng đang hoạt động tối đa phải lớn hơn hoặc bằng không.",
      "workspaces.form.name": "Tên không gian làm việc",
      "workspaces.form.nameRequired": "Tên không gian làm việc là bắt buộc.",
      "workspaces.form.searchRoles": "Tìm kiếm vai trò đang hoạt động",
      "workspaces.impersonation.cancel": "Hủy",
      "workspaces.impersonation.close": "Đóng hộp thoại mạo danh không gian làm việc",
      "workspaces.impersonation.continue": "Tiếp tục",
      "workspaces.impersonation.continuing": "Đang tiếp tục...",
      "workspaces.impersonation.error": "Không thể bắt đầu mạo danh. Vui lòng thử lại.",
      "workspaces.impersonation.loadError": "Không thể tải người dùng của không gian làm việc lúc này.",
      "workspaces.impersonation.loadingUsers": "Đang tải người dùng khả dụng...",
      "workspaces.impersonation.noMatchingUsers": "Không có người dùng phù hợp.",
      "workspaces.impersonation.searchUsers": "Tìm kiếm người dùng",
      "workspaces.impersonation.title": "Đăng nhập với tư cách",
      "workspaces.impersonation.user": "Người dùng",
      "workspaces.impersonation.workspace": "Không gian làm việc",
      "workspaces.listError": "Không thể tải danh sách không gian làm việc lúc này.",
      "workspaces.loading": "Đang tải không gian làm việc...",
      "workspaces.loginAs": "Đăng nhập với tư cách",
      "workspaces.noRoles": "Không có vai trò",
      "workspaces.table.actions": "Thao tác",
      "workspaces.table.description": "Mô tả",
      "workspaces.table.edit": "Chỉnh sửa",
      "workspaces.table.editAria": "Chỉnh sửa không gian làm việc",
      "workspaces.table.name": "Tên",
      "workspaces.table.roles": "Vai trò",
      "workspaces.table.status": "Trạng thái",
      "workspaces.title": "Không gian làm việc"
    }
  }
} as const;

export type TranslationKey = keyof typeof resources["en-US"]["translation"];
